{
 "title": "Altai Monitoring",
 "tags": [ "ping_exporter" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "ALTAI Availability",
   "type": "stat",
   "description": "ICMP ping packet lost,  jika lost 100% maka warnanya merah.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ping_loss_percent", "legendFormat": "{{target}}" }
   ]
  },
  {
   "title": "PING RTT",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "ping_rtt_mean_ms", "legendFormat": "{{target}}" }
   ]
  },
  {
   "title": "Altai Lost Packet Detail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "ping_loss_percent > 0", "legendFormat": "{{target}}" }
   ]
  }
 ]
}