{
 "title": "Windows Server Banjarmasin",
 "description": "Basic overview of windows host metrics, based on Windows Exporter",
 "tags": [ "windows" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(windows_os_time, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Host Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime | $job",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "windows_os_time{job=~\"$job\"} - windows_system_system_up_time{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Processors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "repeat": "host",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "windows_cs_logical_processors{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "repeat": "host",
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - avg(irate(windows_cpu_time_total{job=~\"$job\",mode=\"idle\"}[5m])) > 0"
    }
   ]
  },
  {
   "title": "Net IN (24h)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "repeat": "host",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(windows_net_bytes_received_total{job=\"$job\"}[24h]))"
    }
   ]
  },
  {
   "title": "UP (Success Pull)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{job=\"$job\"}",
     "legendFormat": "up"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "repeat": "host",
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "windows_cs_physical_memory_bytes{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Memory Load",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "repeat": "host",
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - (windows_os_physical_memory_free_bytes{job=\"$job\"} / windows_cs_physical_memory_bytes{job=\"$job\"}) > 0"
    }
   ]
  },
  {
   "title": "Net OUT (24h)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
   "repeat": "host",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(windows_net_bytes_sent_total{job=\"$job\"}[24h]))"
    }
   ]
  },
  {
   "title": "Disk (Free)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_logical_disk_free_bytes{job=\"$job\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Disk Usage %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - windows_logical_disk_free_bytes{job=\"$job\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"} / windows_logical_disk_size_bytes{job=\"$job\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"} > 0",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  { "title": "Disk Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Disk (Free) | $job",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "repeat": "host",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "windows_logical_disk_free_bytes{job=\"$job\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Disk Activity | $job",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "repeat": "host",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "- irate(windows_logical_disk_write_bytes_total{job=\"$job\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}[5m]) < 0",
     "legendFormat": "Write {{volume}}"
    },
    {
     "expr": "irate(windows_logical_disk_read_bytes_total{job=\"$job\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}[5m]) > 0",
     "legendFormat": "Read {{volume}}"
    }
   ]
  },
  {
   "title": "Disk IO | $job",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "repeat": "host",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "- irate(windows_logical_disk_write_seconds_total{job=\"$job\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}[5m]) < 0",
     "legendFormat": "Write {{volume}}"
    },
    {
     "expr": "irate(windows_logical_disk_read_seconds_total{job=\"$job\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}[5m]) > 0",
     "legendFormat": "Read {{volume}}"
    }
   ]
  },
  { "title": "CPU Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "CPU Load | $job",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "repeat": "host",
   "yaxes": [
    { "format": "short", "label": "Load" }
   ],
   "targets": [
    {
     "expr": "sum by (mode) (irate(windows_cpu_time_total{job=\"$job\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "System Exceptions | $job",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 26 },
   "repeat": "host",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(windows_system_exception_dispatches_total{job=\"$job\"}[5m])",
     "legendFormat": "exceptions"
    }
   ]
  },
  {
   "title": "System Threads | $job",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 26 },
   "repeat": "host",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "windows_system_threads{job=\"$job\"}",
     "legendFormat": "threads"
    }
   ]
  },
  { "title": "Memory Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Memory | $job",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
   "repeat": "host",
   "yaxes": [
    { "format": "bytes", "label": "RAM" }
   ],
   "targets": [
    {
     "expr": "windows_os_virtual_memory_bytes{job=\"$job\"} > 0",
     "legendFormat": "Virtual"
    },
    {
     "expr": "windows_cs_physical_memory_bytes{job=\"$job\"} > 0",
     "legendFormat": "Physical"
    },
    {
     "expr": "windows_os_physical_memory_free_bytes{job=\"$job\"} > 0",
     "legendFormat": "Free"
    }
   ]
  },
  { "title": "Network Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Network Traffic (Hour) | $job",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 41 },
   "repeat": "host",
   "yaxes": [
    { "format": "bytes", "label": "transmit (-) /receive (+)" }
   ],
   "targets": [
    {
     "expr": "increase(windows_net_bytes_received_total{job=\"$job\"}[60m])",
     "legendFormat": "Received"
    },
    {
     "expr": "increase(windows_net_bytes_sent_total{job=\"$job\"}[60m])",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Net IN (Hour)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 41 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(windows_net_bytes_received_total{job=\"$job\"}[1h]))"
    }
   ]
  },
  {
   "title": "Net OUT (Hour)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 41 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(windows_net_bytes_sent_total{job=\"$job\"}[1h]))"
    }
   ]
  },
  {
   "title": "Network discarded/error | $job",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 46 },
   "repeat": "host",
   "yaxes": [
    { "format": "pps", "label": "Load" }
   ],
   "targets": [
    {
     "expr": "irate(windows_net_packets_outbound_discarded{job=\"$job\",nic!~\"isatap.+\"}[5m]) + irate(windows_net_packets_outbound_errors{job=\"$job\"}[5m])",
     "legendFormat": "Sent ({{nic}})"
    },
    {
     "expr": "irate(windows_net_packets_received_discarded{job=\"$job\", nic!~\"isatap.+\"}[5m]) + irate(windows_net_packets_received_errors{job=\"$job\"}[5m])",
     "legendFormat": "Received ({{nic}})"
    }
   ]
  }
 ]
}