global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'email'

receivers:
- name: 'email'
  email_configs:
  - to: 'whois.muchlis@gmail.com,mulyo.wardoyo@pelindo.co.id,isa.kurniawan@pelindo.co.id,andi.susilo@pelindo.co.id,gema.eqbal@pelindo.co.id,ahmad.muzahid@pelindo.co.id,hendra.kurniawan@pelindo.co.id,aidil.fitri@pelindo.co.id'
    from: 'itsuppbjm@gmail.com'
    smarthost: smtp.gmail.com:587
    auth_username: 'itsuppbjm@gmail.com'
    auth_identity: 'itsuppbjm@gmail.com'
    auth_password: '****************'
    send_resolved: false

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
